# Generated by Django 5.1.1 on 2024-12-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('vehicle_name', models.CharField(max_length=40)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=5)),
                ('date_joined', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_img', models.FileField(upload_to='')),
                ('vehicle_img', models.FileField(upload_to='')),
            ],
        ),
    ]
