# Generated by Django 5.0.6 on 2024-12-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('emailid', models.EmailField(max_length=254, unique=True)),
                ('mob_number', models.CharField(max_length=15)),
                ('licensenumber', models.CharField(max_length=100)),
                ('licensepic', models.FileField(upload_to='')),
                ('userpic', models.FileField(upload_to='')),
                ('signpic', models.FileField(upload_to='')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
