# Generated by Django 5.0.6 on 2025-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_loginuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
