# Generated by Django 5.0.6 on 2025-01-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_bookvehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='profile_img',
            new_name='provider_img',
        ),
    ]
