# Generated by Django 5.0.6 on 2025-01-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
