# Generated by Django 5.0.6 on 2025-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Value', max_length=100)),
                ('booking_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('dropoff_date', models.DateField()),
                ('dropoff_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookvehicle',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bookvehicle',
            name='price_per_week',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
