# Generated by Django 5.0.6 on 2025-02-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='57FA02A8', editable=False, max_length=20, unique=True),
        ),
    ]
