# Generated by Django 5.0.6 on 2025-02-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
    ]
